spring:
  application:
  name: product
  jpa:
    show-sql: true
    databasePlatform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_iphone?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: admin123
#server:
#  port: 8080
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8888/eureka/
#security:
#  oauth2:
#    client:
#      clientId: user-service
#      clientSecret: user-service
#      accessTokenUri: http://localhost:8762/oauth/token
#      grant-type: client_credentials
#      scope: server
#    resource:
#      userInfoUri: http://localhost:8762/auth/user